[[main]]
  name = 'About'
  pageRef = '/about'
  weight = 10

[[main]]
  name = 'Downloads'
  pageRef = '/downloads'
  weight = 20

[[main]]
  name = 'Releases'
  pageRef = '/releases'
  weight = 30

[[main]]
  name = 'Contributors'
  pageRef = '/contributors'
  weight = 40

[[main]]
  name = 'Docs'
  pageRef = '/docs'
  weight = 50

[[main]]
  name = 'Bots'
  pageRef = '/bots'
  weight = 60

[[main]]
  name = 'Simulator'
  pageRef = '/simulator'
  weight = 70

[[main]]
  name = 'Contribute'
  pageRef = '/contribute'
  weight = 80

[[footer]]
  name = 'FAQ'
  pageRef = '/faq'
  weight = 10

[[footer]]
  name = 'Disclaimer'
  pageRef = '/disclaimer'
  weight = 20

[[footer]]
  name = 'GitHub'
  url = 'https://github.com/SZXC-WG/LocalGen-new'
  weight = 30
