[[main]]
  name = 'Docs'
  pageRef = '/docs'
  weight = 10
[[main]]
  name = 'Bot'
  pageRef = '/bots'
  weight = 20
[[main]]
  name = 'Simulator'
  pageRef = '/simulator'
  weight = 30
[[main]]
  name = 'About'
  pageRef = '/about'
  weight = 40
