[[main]]
  name = '소개'
  pageRef = '/about'
  weight = 10

[[main]]
  name = '다운로드'
  pageRef = '/downloads'
  weight = 20

[[main]]
  name = '릴리스'
  pageRef = '/releases'
  weight = 30

[[main]]
  name = '기여자'
  pageRef = '/contributors'
  weight = 40

[[main]]
  name = '문서'
  pageRef = '/docs'
  weight = 50

[[main]]
  name = '봇'
  pageRef = '/bots'
  weight = 60

[[main]]
  name = '시뮬레이터'
  pageRef = '/simulator'
  weight = 70

[[main]]
  name = '기여하기'
  pageRef = '/contribute'
  weight = 80

[[footer]]
  name = 'FAQ'
  pageRef = '/faq'
  weight = 10

[[footer]]
  name = '면책 조항'
  pageRef = '/disclaimer'
  weight = 20

[[footer]]
  name = 'GitHub'
  url = 'https://github.com/SZXC-WG/LocalGen-new'
  weight = 30
