[[main]]
  name = '文档'
  pageRef = '/docs'
  weight = 10
[[main]]
  name = 'Bot'
  pageRef = '/bots'
  weight = 20
[[main]]
  name = '模拟器'
  pageRef = '/simulator'
  weight = 30
[[main]]
  name = '关于'
  pageRef = '/about'
  weight = 40
